services:
  node:
    image: node:latest
    build: ./src/node
    ports:
      - 3001:3001
    restart: always


  php:
    image: php:latest
    build: ./src/php
    ports:
      - 8080:80
    restart: always

  lua:
    build: .
    ports:
      - 3002:3002
    restart: always
    command: lua main.lua

  java:
    build: .
    ports:
      - "3000:3000"
    command: java -cp /src/java Main

  python:
    build: ./src/python
    image: python:latest
    ports:
      - 8082:8082
    restart: always