version: '3'

services:
  node:
    build: ./src/node
    ports:
      - 3001:3001
    restart: always
    command: node app.js

  php:
    build: ./src/php
    ports:
      - 8080:80
    restart: always
    command: php -S 0.0.0.0:80

  lua:
    build: ./src/lua
    ports:
      - 3002:3002
    restart: always
    command: lua main.lua

  python:
    build: ./src/python
    ports:
      - 8082:8082
    restart: always
    command: python app.py