version: '3.8'

services:
  python:
    build: ./python
    ports:
      - 5000:5000
    restart: always
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    command: python -c "import datetime; print('Hello ASL! ' + datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S'))"

  php:
    build: ./php
    ports:
      - 8080:80
    restart: always
    environment:
      - COMPOSER_HOME=app/composer
      - COMPOSER_CACHE_DIR=app/composer/cache
    command: php -r "echo 'Hello ASL! ' . date('Y-m-d H:i:s') . PHP_EOL;"

  node:
    build: ./node
    ports:
      - 3001:3001
    restart: always
    environment:
      - NODE_ENV=development
    command: node -e "console.log('Hello ASL! ' + new Date())"

  lua:
    build: ./lua
    ports:
      - 3002:3002
    restart: always
    environment:
      - LUA_PATH=/app/?.lua
    command: lua -e "print('Hello ASL! ' .. os.date('%Y-%m-%d %H:%M:%S'))"

  java:
    build: ./java
    ports:
      - 8081:8081
    restart: always
    environment:
      - JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
    command: java -cp target/myapp.jar com.example.MyApp

volumes:
  db-data: