services:
  node:
    build: ./src/node
    ports:
      - 3001:3001
    restart: always
    command: node src/node/index.js


  php:
    build: ./src/php
    ports:
      - 8080:80
    restart: always
    command: php src/php/index.php


  lua:
    image: alpine
    ports:
      - 3002:3002
    restart: always
    command: lua src/lua/main.lua

  java:
    build:
      context: ./src/java
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    restart: always
    command: java src/java/Main.java

  python:
    build: ./src/python
    image: python:latest
    ports:
      - 8082:8082
    restart: always
    command: python src/python/main.py