FROM alpine:latest

RUN apk add curl make gcc musl-dev

RUN curl -L -R -O https://www.lua.org/ftp/lua-5.4.7.tar.gz
RUN tar zxf lua-5.4.7.tar.gz
WORKDIR lua-5.4.7
RUN make linux
RUN make install
CMD ["lua"]